spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

kakao:
  auth:
    client-id: 4b5c5b6d6f920a0fe945665f2da2648a
    redirect-uri: http://localhost:8080/auth/login/kakao

  local:
    api-key: 4b5c5b6d6f920a0fe945665f2da2648a
    reverse-geocode-url: https://dapi.kakao.com/v2/local/geo/coord2address.json # 좌표->주소 변환 API URL

cloud:
    aws:
      credentials:
       access-key: YOUR_AWS_ACCESS_KEY # IAM 사용자에게 발급받은 액세스 키
       secret-key: YOUR_AWS_SECRET_KEY # IAM 사용자에게 발급받은 시크릿 키
      s3:
        bucket: return-zone
      region:
        static: ap-northeast-2
      stack:
        auto: false